# Generated by Django 4.0.5 on 2022-09-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField(max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('product_id', models.ManyToManyField(blank=True, to='product.product')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
