# Generated by Django 4.0.5 on 2022-09-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_amount_remove_order_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='amount',
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='quantity',
            field=models.PositiveIntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
